'use strict';
// tests for graphql
// Generated by serverless-mocha-plugin

const mod         = require('../resource/graphql/handler');
const mochaPlugin = require('serverless-mocha-plugin');
const wrapper     = mochaPlugin.lambdaWrapper;
const expect      = mochaPlugin.chai.expect;

wrapper.init(mod);

describe('graphql', () => {
  it('implement tests here', (done) => {
    wrapper.run({}, (err, response) => {
      expect(err).to.be.null;
      expect(response).not.to.be.null;
      done();
    });
  });
});
